
apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
spec:
  replicas: 1
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: nexus.daf.teamdigitale.it/kafka-consumer:1.0.0
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
      hostAliases:
      - ip: "192.168.0.21"
        hostnames:
          - "edge2.platform.daf.gov.it"
          - "edge2"
      - ip: "192.168.0.27"
        hostnames:
          - "edge3.platform.daf.gov.it"
          - "edge3"
      - ip: "192.168.0.53"
        hostnames:
          - "edge4.platform.daf.gov.it"
          - "edge4"
      - ip: "192.168.0.54"
        hostnames:
          - "edge5.platform.daf.gov.it"
          - "edge5"